export const game2 = [
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Lovich',
    resources: {
      sheep: 1,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Marthe',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 1,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'NickTheSwift',
    resources: {
      sheep: 0,
      wheat: 0,
      brick: 1,
      tree: 2,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Merril',
    resources: {
      sheep: 0,
      wheat: 1,
      brick: 2,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'ROBBER_STEAL',
    stealerName: 'Lovich',
    victimName: 'Merril',
    stolenResource: null,
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Lovich',
    offeredResources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Merril',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Lovich',
    resources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'NickTheSwift',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Marthe',
    resources: {
      sheep: 0,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Lovich',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_LOSS',
    playerName: 'NickTheSwift',
    resources: {
      tree: 1,
      brick: 1,
    },
  },
  {
    type: 'ROBBER_STEAL',
    stealerName: 'Merril',
    victimName: 'Lovich',
    stolenResource: null,
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Merril',
    offeredResources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Merril',
    resources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Lovich',
    offeredResources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'NickTheSwift',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Marthe',
    resources: {
      sheep: 0,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Lovich',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Marthe',
    offeredResources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Merril',
    resources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'NickTheSwift',
    offeredResources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE',
    player1: 'NickTheSwift',
    player2: 'Merril',
    resourceChanges: {
      sheep: -1,
      wheat: 1,
    },
  },
  {
    type: 'RESOURCE_LOSS',
    playerName: 'NickTheSwift',
    resources: {
      tree: 1,
      wheat: 1,
      brick: 1,
      sheep: 1,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'NickTheSwift',
    resources: {
      sheep: 0,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 2,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Marthe',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Merril',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'BANK_TRADE',
    playerName: 'Merril',
    resourceChanges: {
      sheep: -3,
      tree: 1,
    },
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Merril',
    offeredResources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE',
    player1: 'Merril',
    player2: 'Marthe',
    resourceChanges: {
      wheat: -1,
      ore: 1,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'NickTheSwift',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Marthe',
    resources: {
      sheep: 0,
      wheat: 0,
      brick: 1,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_GAIN',
    playerName: 'Lovich',
    resources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Lovich',
    offeredResources: {
      sheep: 0,
      wheat: 1,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'ROBBER_STEAL',
    stealerName: 'Marthe',
    victimName: 'Merril',
    stolenResource: null,
  },
  {
    type: 'TRADE_OFFER',
    playerName: 'Marthe',
    offeredResources: {
      sheep: 1,
      wheat: 0,
      brick: 0,
      tree: 0,
      ore: 0,
    },
  },
  {
    type: 'RESOURCE_LOSS',
    playerName: 'Marthe',
    resources: {
      wheat: 1,
      sheep: 1,
      ore: 1,
    },
  },
];
